"""Adiciona tabelas de servicos e documentos

Revision ID: d2fde5095000
Revises: 
Create Date: 2025-09-08 13:37:13.464057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2fde5095000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('documentos_gerados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('dados_formulario', sa.JSON(), nullable=False),
    sa.Column('caminho_pdf_final', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mov_estoque', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('mov_estoque_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('mov_estoque_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['id_usuario'], ['id_usuario'])
        batch_op.create_foreign_key(None, 'produto', ['id_produto'], ['Id_produto'])

    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.alter_column('Codigo',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('Preco',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('produto_fornecedor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('FK_PRODUTO_FORNECEDOR_PRODUTO'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('FK_PRODUTO_FORNECEDOR_FORNECEDOR'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'fornecedor', ['FK_FORNECEDOR_id_fornecedor'], ['id_fornecedor'])
        batch_op.create_foreign_key(None, 'produto', ['FK_PRODUTO_Id_produto'], ['Id_produto'])

    with op.batch_alter_table('produto_natureza', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('FK_PRODUTO_NATUREZA_PRODUTO'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('FK_PRODUTO_NATUREZA_NATUREZA'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'natureza', ['fk_NATUREZA_id_natureza'], ['id_natureza'])
        batch_op.create_foreign_key(None, 'produto', ['fk_PRODUTO_Id_produto'], ['Id_produto'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto_natureza', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK_PRODUTO_NATUREZA_NATUREZA'), 'natureza', ['fk_NATUREZA_id_natureza'], ['id_natureza'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('FK_PRODUTO_NATUREZA_PRODUTO'), 'produto', ['fk_PRODUTO_Id_produto'], ['Id_produto'], ondelete='CASCADE')

    with op.batch_alter_table('produto_fornecedor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK_PRODUTO_FORNECEDOR_FORNECEDOR'), 'fornecedor', ['FK_FORNECEDOR_id_fornecedor'], ['id_fornecedor'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('FK_PRODUTO_FORNECEDOR_PRODUTO'), 'produto', ['FK_PRODUTO_Id_produto'], ['Id_produto'], ondelete='CASCADE')

    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.alter_column('Preco',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('Codigo',
               existing_type=sa.String(length=20),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)

    with op.batch_alter_table('mov_estoque', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mov_estoque_ibfk_2'), 'usuario', ['id_usuario'], ['id_usuario'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('mov_estoque_ibfk_1'), 'produto', ['id_produto'], ['Id_produto'], ondelete='RESTRICT')

    op.drop_table('documentos_gerados')
    op.drop_table('servico')
    # ### end Alembic commands ###
